"""Central configuration for the A-share 5-minute data pipeline."""
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent
CTO_DAILY_RAW_DIR = PROJECT_ROOT / "data" / "cto_baostock" / "daily_raw"
STOCK_LIST_PATH = PROJECT_ROOT / "stock_list.csv"
DATA_DIR = PROJECT_ROOT / "data"
RAW_5MIN_DIR = DATA_DIR / "raw_5min"
SEGMENT_5MIN_DIR = RAW_5MIN_DIR / "segments"
DAILY_REFERENCE_DIR = DATA_DIR / "daily_reference_unadjusted"
QC_REPORT_DIR = DATA_DIR / "qc_report"
RECONCILIATION_INVESTIGATION_DIR = QC_REPORT_DIR / "reconciliation_investigation"
PRECISION_INVESTIGATION_DIR = QC_REPORT_DIR / "precision_materiality"
REGIME_REPORT_DIR = QC_REPORT_DIR / "regime_100"
SCALING_INVESTIGATION_DIR = QC_REPORT_DIR / "scaling_factor"
PROCESSED_5MIN_DIR = DATA_DIR / "processed_5min"
FEATURES_5MIN_DIR = DATA_DIR / "features_5min"
DATASET_DIR = DATA_DIR / "dataset"
SEQ_DATASET_DIR = DATASET_DIR / "seq"
FLAT_DATASET_DIR = DATASET_DIR / "flat"
BASELINE_REPORT_DIR = DATA_DIR / "baseline_report"
STAGE3_REPORT_DIR = DATA_DIR / "stage3_report"
STAGE4_REPORT_DIR = DATA_DIR / "stage4_report"
STAGE4_ARTIFACT_DIR = DATA_DIR / "stage4_artifacts"
PLOT_CACHE_DIR = DATA_DIR / ".plot_cache"
PROBE_REPORT_DIR = QC_REPORT_DIR / "probe"
PROGRESS_PATH = RAW_5MIN_DIR / "progress.json"
FAILED_LOG_PATH = RAW_5MIN_DIR / "failed.log"
DOWNLOAD_LOG_PATH = RAW_5MIN_DIR / "download.log"

LIQUIDITY_START_DATE = "2024-01-01"
LIQUIDITY_STOCK_COUNT = 100
LIQUIDITY_SCAN_WORKERS = 4

MINUTE_FIELDS = "date,time,code,open,high,low,close,volume,amount"
DAILY_REFERENCE_FIELDS = "date,code,open,high,low,close,volume,amount,adjustflag,tradestatus"
MINUTE_FREQUENCY = "5"
UNADJUSTED_FLAG = "3"
DOWNLOAD_START_DATE = "2019-01-01"
DEFAULT_WORKERS = 2
REQUEST_SLEEP_SECONDS = 0.1
RETRY_ATTEMPTS = 3
BACKOFF_BASE_SECONDS = 2.0
PARQUET_COMPRESSION = "snappy"
COVERAGE_GAP_YEAR = 2019
COVERAGE_PROBE_STOCKS = 20
PROGRESS_VERSION = 1

EXPECTED_BAR_TIMES = tuple(
    [f"{hour:02d}:{minute:02d}:00" for hour, minute in
     [(9, minute) for minute in range(35, 60, 5)]
     + [(10, minute) for minute in range(0, 60, 5)]
     + [(11, minute) for minute in range(0, 31, 5)]
     + [(13, minute) for minute in range(5, 60, 5)]
     + [(14, minute) for minute in range(0, 60, 5)]
     + [(15, 0)]]
)
EXPECTED_BARS_PER_DAY = 48
SPECIAL_DAY_MIN_COVERAGE_RATIO = 0.5
PRICE_TOLERANCE = 0.01
AMOUNT_ABSOLUTE_TOLERANCE = 0.01
VOLUME_ABSOLUTE_TOLERANCE = 0.0
HIGH_LOW_OPEN_MATCH_TOLERANCE = 0.01
HIGH_LOW_EXPLANATION_RATIO = 0.7
PLOT_DPI = 150
PLOT_BINS = 50
DIAGNOSTIC_FIGURES = 5

BLOCK_TRADE_START_DATE = "2020-01-01"
BLOCK_TRADE_PAGE_LIMIT = 5000
EVENT_REQUEST_SLEEP_SECONDS = 0.2
EVENT_RETRY_ATTEMPTS = 3
BLOCK_MATCH_ABSOLUTE_SHARES = 100.0
BLOCK_MATCH_RELATIVE_TOLERANCE = 0.01
FIXED_PRICE_RELATIVE_TOLERANCE = 0.001
CROSS_VENDOR_VOLUME_TOLERANCE_SHARES = 1.0
FACTOR_CHANGE_TOLERANCE = 1e-10
CLOSE_SAMPLE_SIZE = 20
ROUNDING_SHARE_QUANTUM = 100.0
ROUNDING_MAX_ERROR_PER_BAR = ROUNDING_SHARE_QUANTUM / 2
ROUNDING_RANDOM_WALK_STD_PER_BAR = ROUNDING_SHARE_QUANTUM / (12**0.5)
PRECISION_REGIME_START_DATE = "2023-08-09"
ROUNDING_LIKE_REGIME_START_DATE = "2025-03-20"
REGIME_MIN_STOCK_DAYS = 20
REGIME_PRE_MAX_LARGE_GAP_SHARE = 0.15
REGIME_MAIN_MIN_LARGE_GAP_SHARE = 0.75
REGIME_POST_MAX_LARGE_GAP_SHARE = 0.35
REGIME_START_SEARCH_WINDOW = ("2023-07-01", "2023-10-01")
REGIME_END_SEARCH_WINDOW = ("2025-02-01", "2025-05-01")
SECOND_SOURCE_CODES = ("sz.300308", "sh.601138", "sh.688256")
SECOND_SOURCE_PROBE_DATE = "2026-06-17"
VOLUME_FEATURE_LOOKBACK_DAYS = 20
SCALING_FACTOR_START_DATE = "2023-08-09"
SCALING_FACTOR_END_DATE = "2025-03-19"
FACTOR_RATIO_MATCH_TOLERANCE = 0.0001
FACTOR_STEP_CV_TOLERANCE = 0.0001
FACTOR_EXPLANATION_REQUIRED_SHARE = 0.9
REPAIR_REPORT_PATH = QC_REPORT_DIR / "volume_rescale_audit.csv"
SCALE_GATE_PATH = QC_REPORT_DIR / "scale_gate.csv"
PILOT_SCALE_STOCK_COUNT = 100

FEATURE_MIN_VOL_HISTORY_DAYS = 5
FEATURE_VOL_LOOKBACK_DAYS = 20
LABEL_RANK_MIN_STOCKS = 30
LABEL_30M_BARS = 6
LABEL_60M_BARS = 12
SEQUENCE_LOOKBACK_BARS = 48
SAMPLE_BAR_TIMES = ("10:05:00", "10:35:00", "11:05:00",
                    "13:35:00", "14:05:00", "14:35:00")
SEQUENCE_FEATURE_COLUMNS = (
    "ret_5m", "range_rel", "pos_in_bar", "vol_log", "vol_rel_20d",
    "ret_overnight", "is_first_bar", "time_of_day_sin", "time_of_day_cos",
)
FLAT_CURRENT_FEATURE_COLUMNS = SEQUENCE_FEATURE_COLUMNS
TRAIN_YEARS = 2
VALID_MONTHS = 3
TEST_MONTHS = 6
ROLL_STEP_MONTHS = 6
PURGE_CALENDAR_DAYS = 1
MIN_EXPECTED_TRAIN_SAMPLES = 500_000
DECILE_COUNT = 10
BASELINE_RANDOM_SEED = 20260807
STAGE3_SEEDS = (20260807, 20260808, 20260809, 20260810, 20260811)
LABEL_SHUFFLE_ABS_RANKIC_GATE = 0.01
MLP_HIDDEN_SIZE = 128
MLP_HIDDEN_LAYERS = 2
NEURAL_DROPOUT = 0.3
NEURAL_LEARNING_RATE = 1e-3
NEURAL_WEIGHT_DECAY = 1e-2
MLP_BATCH_SIZE = 4096
GRU_HIDDEN_SIZE = 64
GRU_LAYERS = 1
GRU_BATCH_SIZE = 1024
NEURAL_MAX_EPOCHS = 50
NEURAL_EARLY_STOP_PATIENCE = 8
NEURAL_CPU_THREADS = 4
GRU_INCREMENT_RANKIC_GATE = 0.005
NEURAL_SEED_STABILITY_MAX_STD = 0.005
STAGE4_ATTRIBUTION_SEED = STAGE3_SEEDS[0]
ATTRIBUTION_SAMPLES_PER_WINDOW = 400
ATTRIBUTION_STEPS = 32
ATTRIBUTION_EXTREME_SHARE = 0.10
ATTRIBUTION_HEARTBEAT_EVERY = 50
ATTRIBUTION_WINDOW_TIMEOUT_SECONDS = 20 * 60
TRANSACTION_COST_BPS = (5, 10, 20)
DAILY_MIN_SIGNALS = 6
FAILED_GRU_WINDOWS = (2, 8)
LIGHTGBM_CURVE_ITERATION_STEP = 10
PROBE_COVERAGE_START_YEAR = 2019
PROBE_COVERAGE_WINDOW_START = "07-01"
PROBE_COVERAGE_WINDOW_END = "07-07"
PROBE_EARLIEST_CANDIDATE_START = "2020-01-01"
PROBE_EARLIEST_CANDIDATE_END = "2020-01-15"
PROBE_RECENT_TRADING_DAYS = 8
PRICE_MATCH_TOLERANCE = 0.01
